#!/bin/bash
#Define parameters
AMI_NAME=testami
INSTANCE=i-00d30c6d5f20210f3
ASG_NAME="awscliautoscaling"
OLD_LC="awsclitest"
NEW_LC="testlc"

# Create AMI
IMAGE=`aws ec2 create-image --region us-west-2 --instance-id $INSTANCE --name $AMI_NAME  --no-reboot --output text`
#copy image to DR region
copyami(){
aws ec2 copy-image --source-image-id "$IMAGE" --source-region us-west-2 --region us-east-1 --name "$AMI_NAME"
if [ $? -eq 0  ]
then
        echo Image copied successfully to DR Region
else
        echo Failed to Copy image to DR region
fi
}
# Create Launch Configuration
launchconfig(){
aws autoscaling create-launch-configuration --launch-configuration-name "$NEW_LC" --image-id "$IMAGE" --region us-west-2  --instance-type "t2.micro" --key-name "Devops179" --security-groups "sg-00eaea4d4568fb0e4" --iam-instance-profile arn:aws:iam::290686968670:instance-profile/iamtestrole
if [ $? -eq 0  ]
then
        echo Launch configuration created successfully
else
        echo Launch configuration failed
                exit 1
fi
}
# Update Auto Scaling Group to use new Launch Configuration
autoscalingupdate(){
aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME --launch-configuration-name $NEW_LC --region us-west-2
if [ $? -eq 0  ]
then
        echo Auto scaling updated successfully
else
        echo Failed to update auto scaling
fi
}
# Delete old launch-configuration
deleteoldlc(){
aws autoscaling delete-launch-configuration --launch-configuration-name $OLD_LC --region us-west-2
if [ $? -eq 0  ]
then
        echo Deleted the old configuration successfully....!!
else
        echo Failed to delete old configuration successfully
fi
}
activity(){
copyami
launchconfig
autoscalingupdate
deleteoldlc
}
activity;
