- name: demo on blockinfile module
  hosts: all
  tasks:
    - name: add a block to a file
      blockinfile:
        path: /tmp/block.txt
        create: yes
        block: |
          Hello World
  
